### ISSUE TITLE
Not able to use helper when wrong input price sensor is used

### ISSUE THREAD

**Issue by Joebinator** [mampfes/ha_epex_spot_sensor#1]
I used the "net_price" sensor for the price input and now the binary sensor from the integration is of no use. How can i delete it?

<img width="1093" alt="image" src="https://github.com/mampfes/ha_epex_spot_sensor/assets/44570824/a7e616c5-37b9-4525-877b-dce12501ed6d">

PS: When i use the normal price sensor for the price input, it works.

**Comment by mampfes** [comment]
Select the helper --> cog wheel --> delete

**Comment by Joebinator** [comment]
It i click on the helper i only get to the options section 

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/44570824/8c913211-01fc-4008-be2f-c8d35a8a5df3)

**Comment by mampfes** [comment]
On my HA 2024.1 is looks like this:
![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/375950/66f7857e-38aa-46a4-9c51-c77fd1b0365d)
***
![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/375950/38872d93-01d7-4656-be4b-fbdb17123d61)
***
![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/375950/66043ace-fef6-440b-a065-9672969fe015)

**Comment by Joebinator** [comment]
yes, my other epex sensors look the same as yours, only the one that i had configured with the "wrong" **net price sensor** gives that odd behavior

**Comment by Matze-aaa** [comment]
same here. after newstart HA it works, until a new sensor ist created.
Which price-sensor is recommended? I think only the net price sensor has the information about the hourly prices today/tomorrow?
Many thanks!
BTW - the sensor looks very promising ;-)

**Comment by mampfes** [comment]
Ah, now I see. I will fix this issue in a new version of epex spot sensor.

**Comment by mampfes** [comment]
> Which price-sensor is recommended?
Currently only the price sensor is working. I will enhance it so that you can also use the net-price sensor.

**Comment by mampfes** [comment]
@Matze-aaa 
> second Issue - installing via hacs doesn't work.

What is the issue with HACS? It works on my machine.

**Comment by Matze-aaa** [comment]
> @Matze-aaa
> 
> > second Issue - installing via hacs doesn't work.
> 
> What is the issue with HACS? It works on my machine.

Sorry, didnt read you instructions completely 🫣 it works 👍🏻👋🏻
Thx for fixing the problem!

**Comment by Matze-aaa** [comment]
Today it does not work again ☹️
New installation (via hacs) doesn't help.
Even the EPEX Spot Data Price causes the red bubble and the helper is only deletable /working after restart.
Helper is created via settings / Geräte und Dienste/ Helfer erstellen /EPEX Spot sensor

**Comment by mampfes** [comment]
@Matze-aaa Did you already update to the latest version in HACS?

If yes, please share the log.
