### ISSUE TITLE
Another Helper Entity for Start and End-times? 

### ISSUE THREAD

**Issue by Constipated-Monk** [mampfes/ha_epex_spot_sensor#11]
Hey there,

thanks for the addon. i really like the idea and i think it could actually save me a lot of hassle for what i want to do. Though i am not 100% sure if i am able to archive what i want to do with this addon or if i need to think about it differently anyway.

So here it is: i have a simple and dumb home but now with smartmeter and power delivery paid by the hour. i would like to physically display when the next period for the cheapest prices would be. (ESP, MQTT, a nice display. That thing will live on top of my washing machine :) ) i never really found a straight forward way to display the upcoming TIME for the cheapest price. 
Your addon makes this possible but only has a binary sensor for internal automations, but i don't think i have any possibility to display the actual TIME when the binary sensor will be set to ON. 
Is there a simple way to pull this data from your sensor, or could you maybe add another entity which always displays the next time and date for the cheapest prices?

thanks so much!

**Comment by mampfes** [comment]
Could this be a solution for you?
https://community.home-assistant.io/t/epex-spot-and-awattar-electricity-prices/519151/88

**Comment by mampfes** [comment]
Any update on this? Did you had a look at the solution in the link?

**Comment by Constipated-Monk** [comment]
Hi Mampfes, 

sorry i haven't had time to implement my ideas yet. i looked into it and on a first glance it looks promising. I keep you updated if not. thanks ;)

**Comment by mampfes** [comment]
@Jxhannes Not sure if I got your point. Did you check the solution in the link above? It describes a way to create a sensor which tells you the next turn-on-time.
