### ISSUE TITLE
No Helper data for 24h in case one hour has a price of 0cent

### ISSUE THREAD

**Issue by oldman4U** [mampfes/ha_epex_spot_sensor#14]
Any other user having the same issue that the helpers can not get data from sensor.epex_spot_data_price and therefore the status became "Unknown". Could be related to the latest HA Core update. ![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/54359396/cd5ba027-fa9d-4776-8cf0-d08bb37e597d)

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/54359396/0dbb8f63-8db0-453b-952d-22ac41197de7)

**Comment by oldman4U** [comment]
Downgrading to core 2024.3.1 did not help, but could it be that the 0cent/kWh price tomorrow causes this.

<img width="324" alt="Screenshot 2024-03-22 at 22 40 22" src="https://github.com/mampfes/ha_epex_spot_sensor/assets/54359396/b1df628b-16b5-480b-b612-e84b0cefa410">

**Comment by oldman4U** [comment]
Using net price (which is slightly higher) and therefore avoiding a price of 0 eur solves the problem.

<img width="546" alt="Screenshot 2024-03-22 at 22 52 00" src="https://github.com/mampfes/ha_epex_spot_sensor/assets/54359396/5a80bd69-e679-465e-9d7b-97335a5c47b1">

**Comment by mampfes** [comment]
Good catch. Thanks!

**Comment by mampfes** [comment]
fixed in release 1.2.1

**Comment by oldman4U** [comment]
Gerne.

Vielen Dank für die tolle Lösung

**Comment by WimDeceuninck** [comment]
> fixed in release 1.2.1

Hi mampfes, my helper was in status 'unknown' (after it did a perfect job for several months) and release 1.2.1 indead fixed this issue. However the the attributes seems not to be correct any more. See start & end times in the screenshots below.
02/04 21:00 and 03/04 02:00 is not the cheapest time window.
Do you have any idea what could be wrong and how to correct it?

![Screenshot 2024-04-02 230041](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/26a129d1-1baf-477c-b840-2daba3b8987c)
![Screenshot 2024-04-02 225932](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/c393164d-7583-4b05-a0fc-09795b43140d)
