### ISSUE TITLE
Helper attributes start & end times are no longer correct

### ISSUE THREAD

**Issue by WimDeceuninck** [mampfes/ha_epex_spot_sensor#15]
Epex Spot v2.3.5
Epex Spot Sensor v1.2.1
Time zone
(GMT+01:00) Brussels
Country
Belgium

Hi Steffen @mampfes , my helper was in status 'unknown' (after it did a perfect job for several months) and release 1.2.1 indead fixed this issue. However the attributes seems not to be correct any more. See start & end times in the screenshots below.
02/04 21:00 and 03/04 02:00 is not the cheapest time window.
Do you have any idea what could be wrong and how to correct it?

![Screenshot 2024-04-02 230041](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/26a129d1-1baf-477c-b840-2daba3b8987c)
![Screenshot 2024-04-02 225932](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/c393164d-7583-4b05-a0fc-09795b43140d)

_Originally posted by @WimDeceuninck in https://github.com/mampfes/ha_epex_spot_sensor/issues/14#issuecomment-2033096456_
  
   Update 04/04: I have deleted the helpers and created a new ones again, but the issue remains. I guess this has something to do with the winter/summer time change of last 31st of March? 
Anyway, I don't know how I can fix this.  Your help is much appriciated!
Thanks in advance!
![Screenshot 2024-04-04 212459](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/a0889afe-4c72-40c8-afa0-595bb693737d)
![Screenshot 2024-04-04 212434](https://github.com/mampfes/ha_epex_spot_sensor/assets/136184765/1e67bbe2-4e14-4dd1-acc7-e84d3e4e48d7)

**Comment by Joebinator** [comment]
+1

**Comment by flo13github** [comment]
+1
originally postet in #9

hi guys!
i do have a simular problem as discribed above.
epex spot + sensor are up to date but the helper is putting out the hours from the start till duration is reched. no matter how the electricity price is.

i've already reconfigered all helpers and tryed with 'net price' and 'price' but the behaviour is still the same.
edit: epex spot is working fine, i do get all the data from smartenergy.

thanks for your input!

![319693781-15c19dbb-9806-4b80-a76c-201211c667ef](https://github.com/mampfes/ha_epex_spot_sensor/assets/158095736/b1bc6b41-49f0-46a4-a854-6e4efc86a062)

**Comment by Matze-aaa** [comment]
Same here!

**Comment by Matze-aaa** [comment]
Edit : I just downgraded to V1.2.0 and it works fine again!

**Comment by Nick75wien** [comment]
I have the same issue. The sensors always start with the earliest start time although this is not the cheapest one. Just downgraded to 1.2.0 to see if it works again?

**Comment by WimDeceuninck** [comment]
Hi guys, I also downgraded the Epex Spot Sensor to v.1.2.0 and the sensor attributes are correct again.

**Comment by Matze-aaa** [comment]
> Hi guys, I also downgraded the Epex Spot Sensor to v.1.2.0 and the sensor attributes are correct again.

Which data service do you use? Smard or web scraper? If smard, do newly created sensors work?

**Comment by WimDeceuninck** [comment]
> > Hi guys, I also downgraded the Epex Spot Sensor to v.1.2.0 and the sensor attributes are correct again.
> 
> Which data service do you use? Smard or web scraper? If smard, do newly created sensors work?

Hi Matze-aaa, I am using the scraper, but at the moment the Epex Spot scraper and Epex Spot Sensor are unavailable again...

**Comment by mampfes** [comment]
Hi, sorry for the inconveniences. Release 1.2.2 should fix the issue introduced by 1.2.1.

EPEX Spot Web Scraper doesn't provide any data at the moment, but this is causes there are no values available on the epex spot homepage:
![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/375950/a8a6c413-91e5-48e7-b65a-2c869aca534e)

If there are additional problems, please open a new github issue.

**Comment by WimDeceuninck** [comment]
Hi Steffen, thank you very much for you reply! I'll do the update tomorrow and I'll keep you posted with the results!

**Comment by Matze-aaa** [comment]
Thank you! Update seems to work, EPEX Web scraper is online again, too.

**Comment by WimDeceuninck** [comment]
Hi Steffen, 

Just to let you know that I could restore the Epex Spot and Epex Spot Sensor integrations. 

I had to delete the Epex Spot integration because the (Epex Spot) entities remained unavailable. 

Even after installing Epex Spot again, the entities remained unavailable. 

I could restore the Epex Spot integration after upgrading HA core to 2024.4.0. 

And recreate the Epex Spot Sensor again (the existing ones remained unavailable too). 

But both seems to be O.K. right now. 

I hope my automation still works (should be the case in the cheapest time window on 10/04 between 00:00 and 05:00). 

Anyway, thank you very much for your help and your commitment to all users. 

Kind regards, 
Wim 


Van: "Steffen Zimmermann" ***@***.***> 
Aan: "mampfes/ha_epex_spot_sensor" ***@***.***> 
Cc: "w deceuninck" ***@***.***>, "Author" ***@***.***> 
Verzonden: Maandag 8 april 2024 22:14:49 
Onderwerp: Re: [mampfes/ha_epex_spot_sensor] Helper attributes start & end times are no longer correct (Issue #15) 





Hi, sorry for the inconveniences. Release 1.2.2 should fix the issue introduced by 1.2.1. 

EPEX Spot Web Scraper doesn't provide any data at the moment, but this is causes there are no values available on the epex spot homepage: 
[ https://github.com/mampfes/ha_epex_spot_sensor/assets/375950/a8a6c413-91e5-48e7-b65a-2c869aca534e | image.png (view on web) ] 

If there are additional problems, please open a new github issue.
