### ISSUE TITLE
No Remaining Duration Entity

### ISSUE THREAD

**Issue by lask456** [mampfes/ha_epex_spot_sensor#17]
Hello, I would like to use an external sensor for the duration of my washing machine's program at the best price. My washing machine provides the value for the running time of the program with this sensor sensor.washer_dryer_remaining_time but unfortunately I cannot select this sensor in the epex spot entity integration. only the following message appears: no matching entities found. Do you have a hint for me to do this correctly?

**Comment by mampfes** [comment]
Please try release 1.3.0.
