### ISSUE TITLE
Wrong entity state change

### ISSUE THREAD

**Issue by lask456** [mampfes/ha_epex_spot_sensor#18]
Hello, I noticed today that the epex spot sensor predicted that 11:23 would be the best time to turn on my washing machine, but the washing machine was not started until 12:00 because the sensor's attribute was not set to true until 12:00. In my opinion, the washing machine should have turned on at 11:23. Have I configured something wrong or is there a mistake in the code?

**Comment by mampfes** [comment]
Please share a screenshot of your EPEX Spot Sensor configuration.

**Comment by lask456** [comment]
[``](url
![Screenshot_20240513-210130](https://github.com/mampfes/ha_epex_spot_sensor/assets/116111976/c327ee28-f927-4c6e-8dfb-770cffda22cc)
)

**Comment by lask456** [comment]
Sorry, didn't want to close the post.

**Comment by lask456** [comment]
It may help you a little, my washing machine returns the remaining washing time in minutes. I hope this is ok for epex spot sensor.

sensor.waschtrockner_verbleibende_zeit
![grafik](https://github.com/mampfes/ha_epex_spot_sensor/assets/116111976/e1bf096f-084e-4df1-ba80-328b54d51919)

This screenshot shows the epex spot sensor attributes which are correct, but the sensor switches to true one hour later as shown in the attributes.

![grafik](https://github.com/mampfes/ha_epex_spot_sensor/assets/116111976/02e9025a-8fff-4352-980a-f26ff63ac6de)
