### ISSUE TITLE
Use list of calculated intervals

### ISSUE THREAD

**Issue by lask456** [mampfes/ha_epex_spot_sensor#19]
Hello, I would like to access the information from the sensor that tells me when the most favorable time period is. I want to start my washing machine at the best time and want to know immediately via text to speech when the washing program will be finished. Unfortunately, I can't find the information to read this data from the epex spot sensor anywhere. Can you give me an example of how to use the most favorable time of the current day + time?

Here is a screenshot of the information:

![grafik](https://github.com/mampfes/ha_epex_spot_sensor/assets/116111976/b85eb6e5-2b4f-44b9-8741-30fb5cba4fcc)

**Comment by mampfes** [comment]
Not sure if I got your point...

You can access the Data attribute like this from an automation:
{{ state_attr("binary_sensor.epex_spot_sensor", "data") }}

**Comment by lask456** [comment]
Ok. How can I access the hh:mm from the actual day?

**Comment by mampfes** [comment]
Please check the Home Assistant documentation (e.g.: https://www.home-assistant.io/docs/automation/templating/) for such kind of questions.
