### ISSUE TITLE
Request - Allow to configure a "pause" between Time Intervals

### ISSUE THREAD

**Issue by Cebrain** [mampfes/ha_epex_spot_sensor#21]
Hi,

i have a question / feature request and i hope it is understandable.

My problem: I have an water heater in my apartment, which needs about 1-2 hours every 12 hours to completely heat all my water.
What i want to achieve, i want to heat the water dynamically every 6-12 hours for 2 hours with the cheapest price. It does not need to be exactly every 12 hours.

When i configure the sensor for 24 hours (12 AM to 12 AM) it is possible that the 4 hours are Contiguous if they are the cheapest.
If i create 2 different 12h sensors with 2 hours intervals, i would again could end with a 4hour contiguous session. I could limit the time windows more, but then i could miss the cheapest prices.
I think the best way at the moment would be i configure 4* 6hour sensors with 1h intervals. So i could split it in more or less the best way, but i could still end with more expensive prices and it makes the setup more complicated.

Maybe someone have an idea how to configure this or if it would be possible to configure in the plugin.

**Comment by mampfes** [comment]
Hi, I think there is no simple solution for your specific problem. What I would recommend is to use the data provided by the EPEX Spot integration and build an own automation on top of it. This provides the maximum flexibility.
