### ISSUE TITLE
EventType was used from epex_spot_sensor, this is a deprecated alias which will be removed in HA Core 2025.5

### ISSUE THREAD

**Issue by heinemannj** [mampfes/ha_epex_spot_sensor#22]
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206

EventType was used from epex_spot_sensor, this is a deprecated alias which will be removed in HA Core 2025.5.

Use homeassistant.core.Event instead,
please report it to the author of the 'epex_spot_sensor' custom integration

**Comment by mampfes** [comment]
Which version of epex_spot_sensor are you using? I do not see this warning with the latest version. Please verify!

**Comment by heinemannj** [comment]
![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/3251642/cb28b58e-adb3-4891-9065-e886b619549b)

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/3251642/917c9f81-fbaa-4bed-b5e3-6dc58320a2d1)

![image](https://github.com/mampfes/ha_epex_spot_sensor/assets/3251642/3cf656ed-62d3-4d37-ae51-16fa277105c8)

For some strange reasons I was not asked to update both epex packages ...

Sorry for the noise and thanks for your great Apps!
