### ISSUE TITLE
State unknown, when there are no data until the end of the timer

### ISSUE THREAD

**Issue by oe6bhe** [mampfes/ha_epex_spot_sensor#24]
I have an electic water heater and it should heat 3 hours along the day. The earliest time to have a shower is 4am and so there it has to be finished. The latest is 8am and so It is possible to start heating. 

The electricity prices I get directly from EPEX Spot and so at 1pm I should have prices for the next day. When I start my timer at 8am until 4am the status gets unknown, because for the last 4 hours there are no prices and the calculation fails. 

My wish is to start the timer on base of known prices, so start at 8 am and calculate until midnight. When the new prices are received, the remaining time should be recalculated until the end of the timer.

**Comment by mampfes** [comment]
Hi, I think there is no simple solution for your specific problem. What I would recommend is to use the data provided by the EPEX Spot integration and build an own automation on top of it. This provides the maximum flexibility.
