### ISSUE TITLE
edit price source for existing helper?

### ISSUE THREAD

**Issue by drahdiwaberl** [mampfes/ha_epex_spot_sensor#29]
related to [this](https://github.com/mampfes/ha_epex_spot/issues/153) i just wanted to switch the price input for my existing helpers created with the "EPEX Spot Sensor" - but this isn't in the settings/options of the helper :( how can one change it?

![image](https://github.com/user-attachments/assets/a6b3559f-fa2b-478b-ac76-95c247b69dd3)

**Comment by mampfes** [comment]
You have to remove the sensor and create a new one.
