### ISSUE TITLE
Can not add helper 

### ISSUE THREAD

**Issue by Prophet955** [mampfes/ha_epex_spot_sensor#4]
Hello, I cannot add the helpers with the link.

Does anyone have the same problem ?

(This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you are running the latest version of Home Assistant.)

**Comment by mampfes** [comment]
You can also add a helper manually (once you have installed the integration, e.g., via HACS).

Open `Settings` --> `Devices and Services` --> `Helpers`  --> `Create Helper` --> `EPEX Spot Sensor`

**Comment by mampfes** [comment]
Any update on this?

**Comment by nicojanssens** [comment]
@mampfes I'm using your helper atm, didn't experience major problems to get it running. 

The homeassistant integration URL in the manual didn't work, but when installing the helper manually everything worked as expected.

**Comment by mampfes** [comment]
The links require that name resolution via mDNS for homeassistant.local is working correctly. Maybe that is the problem on your environment. The links are working fine on my machine.
